version: '3'

services:
    postgres:
        container_name: inventario_postgres
        image: "postgres:15.2-alpine"
        user: postgres
        environment:
        - POSTGRES_USER=users_ms
        - POSTGRES_PASSWORD=users_ms
        - POSTGRES_DB=users_ms
        ports:
        - 5432:5432
