FROM node:14.17.6-buster-slim

ENV APP $APP
ENV APP_NAME $APP_NAME
ENV APP_PORT $APP_PORT
ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_USER $DATABASE_USER
ENV DATABASE_PASS $DATABASE_PASS
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_TYPE $DATABASE_TYPE
ENV DATABASE_SYNC $DATABASE_SYNC
ENV DB_CONNECTION_TYPE $DB_CONNECTION_TYPE
ENV DATABASE_AUTO_LOAD_ENTITIES $DATABASE_AUTO_LOAD_ENTITIES

ENV JWT_SECRET_KEY_SHA256 $JWT_SECRET_KEY_SHA256
ENV JWT_SECRET_KEY_REFRESH_TOKEN_SHA256 $JWT_SECRET_KEY_REFRESH_TOKEN_SHA256

ENV RABBITMQ_URI $RABBITMQ_URI
ENV RABBITMQ_CONNECTION_WAIT $RABBITMQ_CONNECTION_WAIT
ENV RABBITMQ_EXCHANGE $RABBITMQ_EXCHANGE
ENV RABBITMQ_EXCHANGE_TYPE $RABBITMQ_EXCHANGE_TYPE
ENV RABBITMQ_QUEUE $RABBITMQ_QUEUE

WORKDIR /app
COPY package.json package-lock.json /app/
COPY . /app/
RUN chmod +x /app/docker-entrypoint.sh
ENTRYPOINT ["/app/docker-entrypoint.sh"]